### ISSUE TITLE
Pubdiv Error

### ISSUE THREAD

**Issue by Fhpdevx** [iceland2k14/quick#15]
Hi, i just run your pubdiv code, and it give me this error : Traceback (most recent call last):
  File "C:\Users\datap\Desktop\Pubdiv\pubdiv.py", line 11, in <module>
    import secp256k1 as ice
  File "C:\Users\datap\Desktop\Pubdiv\secp256k1.py", line 98, in <module>
    ice.get_x_to_y.argtypes = [ctypes.c_char_p, ctypes.c_bool, ctypes.c_char_p]   # x,even,ret
    ^^^^^^^^^^^^^^
  File "C:\Python312\Lib\ctypes\__init__.py", line 392, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\ctypes\__init__.py", line 397, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: function 'get_x_to_y' not found

I have double check and see the secp256k1.py and ice_secp256k1.dll was there, thank you

**Comment by Maqsood2300** [comment]
Same problem here 
Attribute error: module.  'secp256k1'   has no attribute pub2upub
